theme = "cocoa-hugo-theme"
baseurl = "https://felixthoemmes.github.io/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
author              = "Felix Thoemmes"
title               = "Felix Thoemmes"
pygmentsuseclasses  = true
disqusShortname     = "https-felixthoemmes-github-io-blog-hugo"
pluralizelisttitles = false
googleAnalytics     = ""

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Publications"
weight                 = -110
identifier             = "publications"
url                    = "/publications/"

[[menu.main]]
name                   = "Teaching"
weight                 = -100
identifier             = "teaching"
url                    = "/teaching/"

[[menu.main]]
name                   = "Open Science"
weight                 = -90
identifier             = "open"
url                    = "/open/"

[[menu.main]]
name                   = "Projects"
weight                 = -80
identifier             = "projects"
url                    = "/projects/"


[[menu.main]]
name                   = "About"
weight                 = -70
identifier             = "about"
url                    = "/about/"

[params]
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Felix Thoemmes"
cachebuster            = true                          
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = ""
email                  = "felix.thoemmes@cornell.edu"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
github                 = "//github.com/felixthoemmes"
highlightjs            = true
highlightjslanguages   = ["R","go"]                        # additional languages not included in the "common" set
lang                   = "en"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = ""                            # appears in the site header when set to a non-empty string
twitter                = "//twitter.com/felixthoemmes"
avatar                 = "img/profile.jpg" #do not use in the same time as gravatar